#!/bin/bash
apt-get update -y
apt-get install samba -y
mv /etc/hostname /etc/oldhostname
cp hostmane /etc/hostname
mv /etc/samba/smb.conf /etc/samba/oldsmb.conf
cp smb.conf /etc/samba/smb.conf
mv /etc/hosts /etc/oldhosts
cp hosts /etc/hosts
mkdir /srv/kozos
chmod 777 /srv/kozos
mkdir /srv/readonly
chmod 755 /srv/readonly
service smbd restart
useradd user2 -c "user2" -g users -m -d /home/user2 -s /bin/bash
passwd user2 
mkdir /srv/user2
chown user2 /srv/user2
chmod 700 /srv/user2
smbpasswd -a user2 
service smbd restart
