#!/bin/bash
sudo -s
apt-get update -y
apt-get upgrade -y
apt-get install samba -y


mv /etc/hostname /etc/oldhostname
cp ./samba/hostmane /etc/hostname
mv /etc/samba/smb.conf /etc/samba/oldsmb.conf
cp ./samba/smb.conf /etc/samba/smb.conf


mkdir /srv/kozos
chmod 777 /srv/kozos
mkdir /srv/readonly
chmod 755 /srv/readonly

service smbd restart
service smbd status
testparm
